### ISSUE TITLE
Configuring SSL in the tentacle server causes crash

### ISSUE THREAD

**Issue by Robert-Nelson** [pandorafms/pandorafms#22] opened 2015-06-01 05:20 UTC
If I follow the instructions for configuring the server to use SSL then it crashes when the first agent connects.  I did some digging and it looks like a SIGSEGV in IO::Socket::SSL at line 1406 which is related to the password callback.  Since  I'm not using a password on the private key I commented out the SSL_passwd_cb parameter in start_ssl.  That stopped the crash at line 1406 and added a new one at 1467 which is handling the SSL_verify_cb which isn't used.

This is on ver 5.1SP2 installed from the appliance CD.

**Comment by nramon** [comment] 2015-06-01 10:30
Hi Robert,
We did fix a SIGSEGV in IO::Socket::SSL a few months ago (it was not related to the password callback though). Could you try the [nightly builds](http://sourceforge.net/projects/pandora/files/Nightlies/5.x/) and let us know if it works for you? That's the version that will be released soon in 5.1SP3. Thank a lot!

**Comment by Robert-Nelson** [comment] 2015-06-01 15:16
I already tried the 6.0 version from the develop branch in git but it still happened.

**Comment by nramon** [comment] 2015-06-02 09:01
Hi Robert,
Would you mind letting me know the exact commands you used to launch the Tentacle server and client so that I can try to reproduce it? Thanks in advance.

**Comment by Robert-Nelson** [comment] 2015-06-02 09:27
I copied the command line from the rc file and added a -v. I didn't change the client from the default. 

sudo -u pandora /usr/bin/tentacle_server -a 0.0.0.0 -p 41121 -s /var/spool/pandora/data_in '-i._.conf:conf;._.md5:md5;.*.zip:collections' -e /etc/pandora/tentacle/pandorafms.cer.pem -k /etc/pandora/tentacle/pandorafms.key.pem -v 

| From: "Ramón Novoa" notifications@github.com
| To: "pandorafms/pandorafms" pandorafms@noreply.github.com
| Cc: "Robert Nelson" robertn@the-nelsons.org
| Sent: Tuesday, June 2, 2015 2:01:25 AM
| Subject: Re: [pandorafms] Configuring SSL in the tentacle server causes crash
| (#22)

| Hi Robert,
| Would you mind letting me know the exact commands you used to launch the
| Tentacle server and client so that I can try to reproduce it? Thanks in
| advance.

| —
| Reply to this email directly or view it on GitHub .

**Comment by nramon** [comment] 2015-06-02 14:14
It's working for me as expected. The server shuts down the connection because the client is not configured to use SSL, but there's no segmentation fault. Could you try with this [version](https://raw.githubusercontent.com/pandorafms/pandorafms/develop/pandora_agents/unix/tentacle_server)  of the Tentacle server? Thanks again.

**Comment by Robert-Nelson** [comment] 2015-06-02 19:06
Here is the result, sometimes the exit happens after the second connect but the first doesn't work

```
[root@pandorafms ~]# sudo -u pandora ~artica/tentacle_server.txt -a 0.0.0.0 -p 41121 -s /var/spool/pandora/data_in '-i.*\.conf:conf;.*\.md5:md5;.*\.zip:collections' -e /etc/pandora/tentacle/pandorafms.cer.pem -k /etc/pandora/tentacle/pandorafms.key.pem -v
[log] Server listening on 0.0.0.0 port 41121 (press <ctr-c> to stop)
[log] Client connected from 127.0.0.1
No certificate verification because neither SSL_ca_file nor SSL_ca_path known at /usr/share/perl5/IO/Socket/SSL.pm line 301 thread 1
[log] Client connected from 127.0.0.1
No certificate verification because neither SSL_ca_file nor SSL_ca_path known at /usr/share/perl5/IO/Socket/SSL.pm line 301 thread 2
[root@pandorafms ~]# 
```

Okay I retried it using a different port so the non SSL clients wouldn't interfere.  It still exits when the second connect happens even though the first was successful:

```
[root@pandorafms ~]# sudo -u pandora ~artica/tentacle_server.txt -a 0.0.0.0 -p 41122 -s /var/spool/pandora/data_in '-i.*\.conf:conf;.*\.md5:md5;.*\.zip:collections' -e /etc/pandora/tentacle/pandorafms.cer.pem -k /etc/pandora/tentacle/pandorafms.key.pem -v
[log] Server listening on 0.0.0.0 port 41122 (press <ctr-c> to stop)
[log] Client connected from 127.0.0.1
No certificate verification because neither SSL_ca_file nor SSL_ca_path known at /usr/share/perl5/IO/Socket/SSL.pm line 301 thread 1
[log] SSL started for 127.0.0.1
[log] Request to send file 'pandorafms.home.the-nelsons.org.1433271340.data' size 3992b from 127.0.0.1
[log] Received file 'pandorafms.home.the-nelsons.org.1433271340.data' size 3992b from 127.0.0.1
[log] Connection closed from 127.0.0.1
[log] Client connected from 127.0.0.1
No certificate verification because neither SSL_ca_file nor SSL_ca_path known at /usr/share/perl5/IO/Socket/SSL.pm line 301 thread 2
[root@pandorafms ~]#
```

**Comment by Robert-Nelson** [comment] 2015-06-03 02:01
Okay I figured it out.  The problem is that Net::SSLeay that is available with CentOS 6.6 is version 1.35.  But that version is not thread-safe, the first version to be thread-safe is 1.44.  I upgraded to the latest on  CPAN and now it works fine.

**Comment by nramon** [comment] 2015-06-03 14:39
Hi Robert,

Good finding. We've compiled Linux binaries for both the Tentacle server
and the Pandora FMS agent for similar reasons. We'll add that one to the
FAQ.

Regards.

On Tue, Jun 02, 2015 at 07:01:12PM -0700, Robert Nelson wrote:

>    Okay I figured it out. The problem is that Net::SSLeay that is available
>    with CentOS 6.6 is version 1.35. But that version is not thread-safe, the
>    first version to be thread-safe is 1.44. I upgraded to the latest on CPAN
>    and now it works fine.
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
> 1. https://github.com/pandorafms/pandorafms/issues/22#issuecomment-108159574
> 2. https://github.com/pandorafms/pandorafms/issues/22#issuecomment-108159574

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es

**Comment by d3ibys** [comment] 2016-03-18 05:54
Hi Guys, I'm trying to set up Pandore with tentacle ssl but I am getting an error. I did the following steps:
1. openssl req -new -x509 -keyout tentaclekey.pem -out tentaclecert.pem -days 360
2. I modified tentacle file on /etc/init.d/tentacle_serverd and I added "-e /etc/pandora/tentaclecert.pem -k /etc/pandora/tentaclekey.pem" on TENTACLE_EXT_OPTS.
3: I restarted the service tentacle.
4. I modified pandora agent file and enabled the ssl support.
5. I restarted the service pandora_agent

After all of them I am getting this error: 

2016/03/18 05:46:46 - [error] - Error sending file '/tmp/2582650cffd8.1458280001.data': [err] SSL connect attempt failed because of handshake problems

I tried to the client with certificates and without certificates. Someone knows how to resolve this issues?

Help please.

Thank you to all. 
I apologies for my English.

**Comment by nramon** [comment] 2016-03-21 14:47
Hello d3ivys,

Could you try with the latest version of the Tentacle client? There have
been a couple of SSL related fixes:

```
https://sourceforge.net/p/tentacled/code/HEAD/tree/trunk/perl/client/bin/tentacle_client
```

Let me know if it works and I'll update the Pandora FMS repo. Thank you.

On Thu, Mar 17, 2016 at 10:54:53PM -0700, d3ivys wrote:

>    Hi Guys, I'm trying to set up Pandore with tentacle ssl but I am getting
>    an error. I did the following steps:
> 1. openssl req -new -x509 -keyout tentaclekey.pem -out tentaclecert.pem
>    -days 360
> 2. I modified tentacle file on /etc/init.d/tentacle_serverd and I added
>    "-e /etc/pandora/tentaclecert.pem -k /etc/pandora/tentaclekey.pem" on
>    TENTACLE_EXT_OPTS.
>    3: I restarted the service tentacle.
> 3. I modified pandora agent file and enabled the ssl support.
> 4. I restarted the service pandora_agent
>    
>    After all of them I am getting this error:
>    
>    2016/03/18 05:46:46 - [error] - Error sending file
>    '/tmp/2582650cffd8.1458280001.data': [err] SSL connect attempt failed
>    because of handshake problems
>    
>    I tried to the client with certificates and without certificates. Someone
>    knows how to resolve this issues?
>    
>    Help please.
>    
>    Thank you to all.
>    I apologies for my English.
>    
>    —
>    You are receiving this because you commented.
>    Reply to this email directly or [1]view it on GitHub
>    
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
> 1. https://github.com/pandorafms/pandorafms/issues/22#issuecomment-198219250
> 2. https://github.com/pandorafms/pandorafms/issues/22#issuecomment-198219250

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es

**Comment by d3ibys** [comment] 2016-03-21 15:54
Hi Ramón. Thank you very much for your answer.

I'll try the suggestions you have given me and I do know how it was with the solution.

**Closed as completed** 2024-10-11 14:38 UTC
