### ISSUE TITLE
Windows Agent unexpected termination on missing disk

### ISSUE THREAD

**Issue by LeCactus** [pandorafms/pandorafms#90] opened 2017-08-25 08:56 UTC
Hi,
I was reinstalling one of our servers after which the disk layout changed. So the W: disk became non-existent. However I was just copying Agent config file from the old server and didn't think about it.
To my surprise it terminates unexpectedly on start with this module in place. Apparently, module_freepercentdisk can bring the whole agent down if said disk is not present.
Tested on v7.0NG.705 and .711. Replicated on Win 7,8,8.1.

Module looks like this
# Free space on disk W: (%) 
module_begin
module_name Free Space Disk W
module_group Server Global
module_type generic_data
module_interval 12
module_freepercentdisk W:
module_unit %
module_description Free space on drive W: 
module_min_warning 10
module_max_warning 20
module_min_critical 0
module_max_critical 10
module_alert_template Disk Space
module_tags attention
module_end

**Comment by nramon** [comment] 2017-09-01 13:17
Hi LeCactus,

Thank you for taking the time to report this bug. It looks like a duplicate of #89, which has just been fixed.

Best regards.

**Closed as completed by nramon** 2017-09-01 13:17 UTC
Labels: duplicate
